engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - spec/**
  - "**.rb"
  - "**.go"  
exclude_paths:
- "Gemfile.lock"
- "test/**"
- "db/**"
- "app/assets/javascripts/jquery.raty.js"
- "app/assets/javascripts/ratyrate.js.erb"